import{a as S,S as q,i}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const w="50762825-7fe49127b3d94f6c93c99dfe1";async function f(r,o=1){return(await S.get("https://pixabay.com/api/",{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",ssafesearch:!0,per_page:15,page:o}})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".loader-wrapper"),m=document.querySelector(".formBtnMore"),p=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:s,largeImageURL:c,tags:e,likes:t,views:a,comments:P,downloads:M})=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${c}">
                    <img class="gallery-image" src="${s}" alt="${e}" />
                </a>
                <div class="info">
                    <p class="info-item"><b>Likes:</b> ${t}</p>
                    <p class="info-item"><b>Views:</b> ${a}</p>
                    <p class="info-item"><b>Comments:</b> ${P}</p>
                    <p class="info-item"><b>Downloads:</b> ${M}</p>
                </div>
            </li>
        `).join("");g.insertAdjacentHTML("beforeend",o),p.refresh()}function v(){g.innerHTML=""}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function $(){m.classList.remove("is-hidden-btn")}function u(){m.classList.add("is-hidden-btn")}function B(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}let n=1,l="",d=0;const R=15,O=document.querySelector(".formBtnMore");O.addEventListener("click",x);async function x(){n++,b();try{const r=await f(l,n);y(r.hits),p.refresh(),B(),n>=d&&(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}finally{L()}}const C=document.querySelector(".form");C.addEventListener("submit",E);async function E(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),n=1,v(),u(),l===""){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b();try{const o=await f(l,n),s=o.hits;if(d=Math.ceil(o.totalHits/R),s.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(s),i.success({message:`We found ${o.totalHits} images.`,position:"topRight"}),n<d?$():(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error("Помилка отримання зображень:",o),i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{L(),r.target.reset()}}
//# sourceMappingURL=index.js.map
