import{a as q,S as w,i}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="50762825-7fe49127b3d94f6c93c99dfe1";async function g(r,o=1){return(await q.get("https://pixabay.com/api/",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader-wrapper"),p=document.querySelector(".formBtnMore"),y=new w(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const o=r.map(({webformatURL:s,largeImageURL:c,tags:e,likes:t,views:a,comments:M,downloads:S})=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${c}">
                    <img class="gallery-image" src="${s}" alt="${e}" />
                </a>
                <div class="info">
                    <p class="info-item"><b>Likes:</b> ${t}</p>
                    <p class="info-item"><b>Views:</b> ${a}</p>
                    <p class="info-item"><b>Comments:</b> ${M}</p>
                    <p class="info-item"><b>Downloads:</b> ${S}</p>
                </div>
            </li>
        `).join("");h.insertAdjacentHTML("beforeend",o),y.refresh()}function $(){h.innerHTML=""}function L(){m.classList.remove("is-hidden")}function P(){m.classList.add("is-hidden")}function d(){p.classList.remove("is-hidden-btn")}function u(){p.classList.add("is-hidden-btn")}function B(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}let n=1,l="",f=0;const R=15,O=document.querySelector(".formBtnMore");O.addEventListener("click",x);async function x(){n++,u(),L();try{const r=await g(l,n);b(r.hits),y.refresh(),B(),n>=f?(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d()}catch{i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}finally{P()}}const C=document.querySelector(".form");C.addEventListener("submit",E);async function E(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),n=1,$(),u(),l===""){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L();try{const o=await g(l,n),s=o.hits;if(f=Math.ceil(o.totalHits/R),s.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(s),i.success({message:`We found ${o.totalHits} images.`,position:"topRight"}),n<f?d():(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error("Помилка отримання зображень:",o),i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{P(),r.target.reset()}}
//# sourceMappingURL=index.js.map
